pub mod sliding_window;

#[cfg(test)]
mod tests {
    use super::*;
    use test::Bencher;
    use test_case::test_case;

    #[test_case("ADOBECODEBANC", "ABC", "BANC"; "example 1")]
    #[test_case("a", "aa", ""; "case 1")]
    #[test_case("a", "a", "a"; "case 2")]
    fn test_sliding_window_solution(s: &str, t: &str, expected: &str) {
        assert_eq!(
            expected.to_string(),
            sliding_window::Solution::min_window(s.to_string(), t.to_string())
        );
    }

    #[bench]
    fn bench_sliding_window_example_1(b: &mut Bencher) {
        b.iter(|| {
            sliding_window::Solution::min_window("ADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANCADOBECODEBANC".to_string(), "ABC".to_string());
        })
    }
}
