name: Rust

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2022-03-13
          override: true
          components: clippy
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
  test:
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run tests
        run: cargo test
  bench:
    needs:
      - test
    runs-on: ubuntu-latest
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Run Bench
        run: cargo bench
